{{ $packageName := replaceAll .Package "%version%" "${PG_MAJOR}" -}}
ARG BASE=ghcr.io/cloudnative-pg/postgresql:{{ .DefaultVersion }}-minimal-{{ .DefaultDistro }}
FROM $BASE AS builder

ARG PG_MAJOR
ARG EXT_VERSION

USER 0

RUN apt-get update && apt-get install -y --no-install-recommends \
      "{{ $packageName }}=${EXT_VERSION}" && \
    rm -rf /var/lib/apt/lists/*

FROM scratch
ARG PG_MAJOR

# Licenses
COPY --from=builder /usr/share/doc/{{ $packageName }}/copyright /licenses/{{ $packageName }}/

# Libraries
COPY --from=builder /usr/lib/postgresql/${PG_MAJOR}/lib/{{ .Name }}* /lib/

# Share
COPY --from=builder /usr/share/postgresql/${PG_MAJOR}/extension/{{ .Name }}* /share/extension/

USER 65532:65532
